server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
#      socket-timeout: 10000
#      connect-timeout: 10000

asset:
  base-url: http://localhost:8082

escrow:
  base-url: http://localhost:8084

smartContract:
  base-url: http://localhost:8085

jwt:
  secret-key: "u8v9wX2z3A5d6F7g8H9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4Y5z6A7b8C9d0E1f"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: ap-southeast-2
    s3:
      bucket: ${S3_BUCKET_NAME}