server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
  cloud:
    compatibility-verifier:
      enabled: false

escrow:
  base-url: http://localhost:8084
