server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
#      socket-timeout: 10000
#      connect-timeout: 10000

  cloud:
    compatibility-verifier:
      enabled: false

asset:
  base-url: http://localhost:8082

escrow:
  base-url: http://localhost:8084

smartContract:
  base-url: http://localhost:8085

market:
  base-url: http://localhost:8086
