server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
#      socket-timeout: 10000
#      connect-timeout: 10000

#  servlet:
#    multipart:
#      max-file-size: 100MB      # 파일 1개 최대
#      max-request-size: 120MB   # 요청 전체 최대(여러 파트 포함)
#
#  cloud:
#    compatibility-verifier:
#      enabled: false

asset:
  base-url: http://localhost:8082

escrow:
  base-url: http://localhost:8084

smartContract:
  base-url: http://localhost:8085
